spring:
  application:
    name: like-service
  mvc:
    servlet:
      path: /api
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/like_storm
    username: root
    password: wcw231407
  data:
    # Redis ??
    redis:
      database: 0
      host: localhost
      #password: xxx
      timeout: 5000
      port: 6379
  # knife4j ???????????????
  knife4j:
    enable: true
    setting:
      language: zh_cn
